package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"dbeans/backend/internal/auth"
)

const (
	// maxImportRows bounds one import to a single atomic request. It also
	// keeps the JSON body comfortably inside serverless request-size limits.
	maxImportRows = 10_000
	// maxImportBodyBytes is the largest request body the endpoint will read.
	maxImportBodyBytes = 8 << 20
	// maxImportErrors caps how many per-row errors a failed import reports.
	maxImportErrors = 20
	// importDiagnoseBudget bounds the extra passes that hunt for further bad
	// rows after the first failure, so a large bad file can't run out the
	// request's own timeout.
	importDiagnoseBudget = 8 * time.Second
)

type importRequest struct {
	Schema  string   `json:"schema"`
	Table   string   `json:"table"`
	Columns []string `json:"columns"`
	// Rows holds one value per entry in Columns, in the same order. A null
	// value is a SQL NULL; the client decides what an empty CSV cell means.
	Rows [][]*string `json:"rows"`
	// DryRun runs the full insert inside a transaction and always rolls it
	// back, so the caller learns exactly what a real import would hit.
	DryRun bool `json:"dryRun"`
}

type importRowError struct {
	// Row is the 1-based position in the request's rows.
	Row     int    `json:"row"`
	Message string `json:"message"`
}

type importResponse struct {
	OK           bool             `json:"ok"`
	DryRun       bool             `json:"dryRun"`
	RowsInserted int              `json:"rowsInserted"`
	Errors       []importRowError `json:"errors,omitempty"`
	// MoreErrors is set when more rows may be failing than Errors lists.
	MoreErrors bool `json:"moreErrors,omitempty"`
}

// validateImport checks everything about an import request that doesn't need
// the rows to hit the database: the mapped columns exist, are writable, aren't
// repeated, every NOT NULL column without a default is covered, and the row
// shape is uniform. A problem here is a malformed request (HTTP 400), as
// opposed to bad data (a per-row error in a normal 200 response).
func validateImport(req importRequest, columns []ColumnInfo) error {
	if req.Schema == "" || req.Table == "" {
		return errors.New("schema and table are required")
	}
	if len(req.Columns) == 0 {
		return errors.New("map at least one column")
	}
	if len(req.Rows) == 0 {
		return errors.New("there are no rows to import")
	}
	if len(req.Rows) > maxImportRows {
		return fmt.Errorf("an import can hold at most %d rows; split the file", maxImportRows)
	}
	byName := make(map[string]ColumnInfo, len(columns))
	for _, c := range columns {
		byName[c.Name] = c
	}
	mapped := make(map[string]bool, len(req.Columns))
	for _, name := range req.Columns {
		col, ok := byName[name]
		if !ok {
			return fmt.Errorf("unknown column %q", name)
		}
		if col.IsGenerated || col.IsIdentity {
			return fmt.Errorf("column %q is generated by the database and can't be imported into", name)
		}
		if mapped[name] {
			return fmt.Errorf("column %q is mapped more than once", name)
		}
		mapped[name] = true
	}
	for _, c := range columns {
		if !mapped[c.Name] && !c.Nullable && c.DefaultValue == nil && !c.IsGenerated && !c.IsIdentity {
			return fmt.Errorf("column %q is required (NOT NULL with no default) but isn't mapped", c.Name)
		}
	}
	for i, row := range req.Rows {
		if len(row) != len(req.Columns) {
			return fmt.Errorf("row %d has %d values but %d columns are mapped", i+1, len(row), len(req.Columns))
		}
	}
	return nil
}

// importInsertSQL builds the single-row INSERT every imported row is run
// through. Values are bound as text parameters, so Postgres itself parses each
// into its column's type — the same contract the row editor relies on.
func importInsertSQL(schema, table string, columns []string) string {
	cols := make([]string, len(columns))
	params := make([]string, len(columns))
	for i, name := range columns {
		cols[i] = pgx.Identifier{name}.Sanitize()
		params[i] = fmt.Sprintf("$%d", i+1)
	}
	return fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s)", pgx.Identifier{schema, table}.Sanitize(), strings.Join(cols, ", "), strings.Join(params, ", "))
}

// insertRowsBatch pipelines one INSERT per row through the transaction in a
// single round trip. It stops at the first failing row and reports its index
// into rows; the transaction is then unusable and the caller must roll back.
func insertRowsBatch(ctx context.Context, tx pgx.Tx, stmt string, rows [][]*string) (failedAt int, failure error) {
	batch := &pgx.Batch{}
	for _, row := range rows {
		args := make([]any, len(row))
		for i, v := range row {
			args[i] = v
		}
		batch.Queue(stmt, args...)
	}
	results := tx.SendBatch(ctx, batch)
	for i := range rows {
		if _, err := results.Exec(); err != nil {
			_ = results.Close()
			return i, err
		}
	}
	return -1, results.Close()
}

// importErrorMessage renders a Postgres error the way a person fixing a CSV
// needs it: what failed, plus the DETAIL line ("Key (id)=(3) already exists.")
// when the server supplied one.
func importErrorMessage(err error) string {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		if pgErr.Detail != "" {
			return pgErr.Message + " — " + pgErr.Detail
		}
		return pgErr.Message
	}
	return err.Error()
}

// runImport inserts every row inside one transaction. With commit it is
// atomic: any failing row rolls the whole import back and nothing is written.
// Either way, when a row fails it keeps looking for more bad rows (up to
// maxImportErrors, within importDiagnoseBudget) by re-running the file minus
// the rows already known to fail, so one fix-and-retry cycle can address many
// problems rather than one at a time.
func runImport(ctx context.Context, conn *pgx.Conn, stmt string, rows [][]*string, commit bool) (importResponse, error) {
	resp := importResponse{DryRun: !commit}

	tx, err := conn.Begin(ctx)
	if err != nil {
		return resp, err
	}
	failedAt, failure := insertRowsBatch(ctx, tx, stmt, rows)
	if failure == nil {
		if commit {
			if err := tx.Commit(ctx); err != nil {
				return resp, err
			}
		} else {
			_ = tx.Rollback(ctx)
		}
		resp.OK = true
		resp.RowsInserted = len(rows)
		return resp, nil
	}
	_ = tx.Rollback(ctx)
	if failedAt < 0 {
		// The batch itself failed rather than one row (connection loss, ...).
		return resp, failure
	}

	// Positions in the original rows that are already known to fail.
	failed := map[int]bool{failedAt: true}
	resp.Errors = []importRowError{{Row: failedAt + 1, Message: importErrorMessage(failure)}}
	deadline := time.Now().Add(importDiagnoseBudget)
	for len(resp.Errors) < maxImportErrors && time.Now().Before(deadline) {
		remaining := make([][]*string, 0, len(rows))
		origin := make([]int, 0, len(rows))
		for i, row := range rows {
			if !failed[i] {
				remaining = append(remaining, row)
				origin = append(origin, i)
			}
		}
		if len(remaining) == 0 {
			return resp, nil
		}
		probe, err := conn.Begin(ctx)
		if err != nil {
			return resp, nil
		}
		at, next := insertRowsBatch(ctx, probe, stmt, remaining)
		_ = probe.Rollback(ctx)
		if next == nil || at < 0 {
			return resp, nil
		}
		failed[origin[at]] = true
		resp.Errors = append(resp.Errors, importRowError{Row: origin[at] + 1, Message: importErrorMessage(next)})
	}
	// Ran out of budget or hit the error cap with rows still unchecked: the
	// listed errors are a sample, not necessarily all of them.
	resp.MoreErrors = true
	return resp, nil
}

// ImportTableRows bulk-inserts mapped CSV rows into one table, atomically.
// The client parses the file and sends values already aligned to target
// columns; the server owns validation, the transaction, and the audit entry.
func (s *Server) ImportTableRows(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, maxImportBodyBytes)
	var req importRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request (an import can be at most 8 MB)")
		return
	}
	user, err := auth.Resolve(r.Context(), s.Pool, bearerToken(r))
	if err != nil {
		writeError(w, http.StatusUnauthorized, "not authenticated")
		return
	}
	connID := chi.URLParam(r, "id")
	s.withTableConnection(w, r, true, func(ctx context.Context, conn *pgx.Conn, _ sqlConnFields) {
		columns, _, tableType, err := tableMetadata(ctx, conn, req.Schema, req.Table)
		if err != nil {
			writeError(w, http.StatusBadRequest, err.Error())
			return
		}
		if tableType != "BASE TABLE" {
			writeError(w, http.StatusBadRequest, "views are read-only")
			return
		}
		if err := validateImport(req, columns); err != nil {
			writeError(w, http.StatusBadRequest, err.Error())
			return
		}
		resp, err := runImport(ctx, conn, importInsertSQL(req.Schema, req.Table, req.Columns), req.Rows, !req.DryRun)
		if err != nil {
			writeError(w, http.StatusBadGateway, importErrorMessage(err))
			return
		}
		if resp.OK && !req.DryRun {
			s.logTableMutation(ctx, r, user, "table_import", map[string]any{
				"connectionId": connID, "schema": req.Schema, "table": req.Table, "columns": req.Columns, "rowsAffected": resp.RowsInserted,
			})
		}
		writeJSON(w, http.StatusOK, resp)
	})
}
